# Generated by Django 4.1.1 on 2022-09-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCommunity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
