# Generated by Django 4.1.1 on 2022-09-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCommunity', '0002_delete_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='camada',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
    ]
